import { StyleSheet } from 'react-native';

const AdminPageStyles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 16,
  },
  header: {
    fontSize: 24,
    fontWeight: 'bold',
  },
  logo: {
    width: 150,
    height: 150,
    marginBottom: 8,
    alignSelf: 'center',
  },
  addButton: {
    padding: 8,
    backgroundColor: '#4CAF50',
    borderRadius: 8,
  },
  addButtonText: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  productItemContainer: {
    flex: 1,
    margin: 8,
    padding: 16,
    borderWidth: 2,
    borderRadius: 8,
    alignItems: 'center',
    borderColor: '#FFFFFF',
    backgroundColor: 'rgba(255, 217, 131, 0.2)',
  },
  sectionContainer: {
    marginBottom: 16,
  },
  productImage: {
    width: 100,
    height: 100,
    borderRadius: 8,
    marginBottom: 8,
  },
  productName: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  productPrice: {
    fontSize: 14,
    color: '#888',
  },
  editButton: {
    backgroundColor: '#2196F3', 
    padding: 8,
    borderRadius: 8,
    marginBottom: 8,
  },
  editButtonText: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  deleteButton: {
    backgroundColor: '#FF0000', 
    padding: 8,
    borderRadius: 8,
  },
  deleteButtonText: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalHeader: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 16,
  },
  modalTextInput: {
    width: 400,
    padding: 8,
    borderWidth: 1,
    borderRadius: 8,
    marginBottom: 16,
    textAlign: 'center',
    backgroundColor: 'rgba(25, 15, 30, 0.5)',
  },
  modalButton: {
    backgroundColor: '#4CAF50', 
    padding: 8,
    borderRadius: 8,
    marginBottom: 8,
  },
  modalButtonText: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalContent: {
    width: '80%',
    padding: 16,
    backgroundColor: 'white',
    borderRadius: 8,
    elevation: 5, 
    alignItems: 'center',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.3)', 
  },
  modalContent: {
    width: '80%',
    padding: 16,
    backgroundColor: 'white',
    borderRadius: 8,
    elevation: 5, 
    alignItems: 'center',
  },
  modalHeader: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 16,
  },
  modalTextInput: {
    width: 400,
    padding: 8,
    borderWidth: 1,
    borderRadius: 8,
    marginBottom: 16,
    textAlign: 'center',
    backgroundColor: 'rgba(25, 15, 30, 0.3)',
  },
  modalButton: {
    backgroundColor: '#4CAF50',
    padding: 8,
    borderRadius: 8,
    marginBottom: 8,
  },
  modalButtonText: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFD983',
    padding: 20,
  },
  modalContent: {
    width: '80%',
    padding: 16,
    backgroundColor: 'white',
    borderRadius: 8,
    elevation: 5,
    alignItems: 'center',
  },
  modalHeader: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 16,
    textAlign: 'center',
  },
  modalTextInput: {
    width: 400,
    padding: 12,
    borderWidth: 1,
    borderRadius: 8,
    marginBottom: 16,
    textAlign: 'center',
    backgroundColor: 'rgba(25, 15, 30, 0.3)',
  },
  modalButton: {
    backgroundColor: '#171716',
    padding: 12,
    borderRadius: 8,
    marginBottom: 8,
  },
  modalButtonText: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
});

export default AdminPageStyles;
